/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyquancafe;

import DataTransfer.NhanVien;
import java.awt.CardLayout;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author HT
 */
public class fmMain extends javax.swing.JFrame {

    private JPanel pnlBH;
    private JPanel pnlDU;
    private JPanel pnlKM;
    private JPanel pnlNH;
    private JPanel pnlNV;
    private CardLayout cl = new CardLayout();
    private NhanVien nhanvien;
    
    /**
     * Creates new form fmMain
     */
    public fmMain(NhanVien nv) {
        initComponents();
        
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width - 5, Toolkit.getDefaultToolkit().getScreenSize().height - 45);
        //this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height - 35);
        this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getSize().width/2,
                         Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getSize().height/2 - 20);
        
        try {
            this.setIconImage(ImageIO.read(new File(System.getProperty("user.dir") + "\\src\\img\\icon.png")));
        } catch (IOException ex) {
            Logger.getLogger(fmDangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        //this.setExtendedState(this.MAXIMIZED_BOTH); // set trạng thái mở rộng
        this.setResizable(false);
        this.setTitle("Phần mềm quản lý quán cafe - 5T team");
        nhanvien = nv;
        lbLoaiNV.setText(nv.getLoaiNV());
        lbNhanVien.setText(nv.getHoTen());
        LoadPanelContent();
        
        
    }

    /**
     * Set layout of pnlContent and add all panel in the pnlContent
     * Default show panel pnlQLBH
     */
    void LoadPanelContent() {
        pnlBH = new pnlQLBH(nhanvien.getLoaiNV());
        pnlDU = new pnlQLDU();
        pnlKM = new pnlQLKM();
        pnlNH = new pnlQLNH();
        pnlNV = new pnlQLNV(nhanvien);
        
        pnlContent.setLayout(cl);
        
        pnlContent.add(pnlBH, "1");
        pnlContent.add(pnlDU, "2");
        pnlContent.add(pnlNH, "3");
        pnlContent.add(pnlKM, "4");
        pnlContent.add(pnlNV, "5");
        
        cl.show(pnlContent, "1");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnQLBH = new javax.swing.JButton();
        btnQLDU = new javax.swing.JButton();
        btnQLNH = new javax.swing.JButton();
        btnQLKM = new javax.swing.JButton();
        btnQLNV = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        lbNhanVien = new javax.swing.JLabel();
        lbLoaiNV = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        pnlMenu.setPreferredSize(new java.awt.Dimension(1361, 100));

        btnQLBH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQLBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logobanhang.png"))); // NOI18N
        btnQLBH.setText("QL bán hàng");
        btnQLBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLBHActionPerformed(evt);
            }
        });

        btnQLDU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQLDU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logodouong.png"))); // NOI18N
        btnQLDU.setText("QL đồ uống");
        btnQLDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDUActionPerformed(evt);
            }
        });

        btnQLNH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQLNH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logomuahang.png"))); // NOI18N
        btnQLNH.setText("QL nhập hàng");
        btnQLNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNHActionPerformed(evt);
            }
        });

        btnQLKM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQLKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logokhuyenmai.png"))); // NOI18N
        btnQLKM.setText("QL khuyến mãi");
        btnQLKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKMActionPerformed(evt);
            }
        });

        btnQLNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logonhanvien.png"))); // NOI18N
        btnQLNV.setText("QL nhân viên");
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        lbNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbNhanVien.setText("jLabel1");

        lbLoaiNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbLoaiNV.setText("jLabel2");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnQLBH, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLDU, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLNH)
                .addGap(18, 18, 18)
                .addComponent(btnQLKM)
                .addGap(18, 18, 18)
                .addComponent(btnQLNV)
                .addGap(48, 48, 48)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNhanVien)
                    .addComponent(lbLoaiNV)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQLDU)
                    .addComponent(btnQLNH)
                    .addComponent(btnQLKM)
                    .addComponent(btnQLBH)
                    .addComponent(btnQLNV))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLoaiNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMenu, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1361, Short.MAX_VALUE)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLBHActionPerformed
        cl.show(pnlContent, "1");
    }//GEN-LAST:event_btnQLBHActionPerformed

    private void btnQLDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDUActionPerformed
        cl.show(pnlContent, "2");
    }//GEN-LAST:event_btnQLDUActionPerformed

    private void btnQLNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNHActionPerformed
        cl.show(pnlContent, "3");
    }//GEN-LAST:event_btnQLNHActionPerformed

    private void btnQLKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKMActionPerformed
        cl.show(pnlContent, "4");
    }//GEN-LAST:event_btnQLKMActionPerformed

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        cl.show(pnlContent, "5");
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        
        PlayMp3 player = new PlayMp3(System.getProperty("user.dir") + "\\src\\Music\\Fur Elise - Richard Clayderman.mp3");
        
        player.Play();
        
    }//GEN-LAST:event_btnPlayActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(fmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(fmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(fmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(fmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new fmMain().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnQLBH;
    private javax.swing.JButton btnQLDU;
    private javax.swing.JButton btnQLKM;
    private javax.swing.JButton btnQLNH;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JLabel lbLoaiNV;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}

class PlayMp3 {

    private Player player;
    private String Url;
    
    public PlayMp3(String url)
    {
        this.Url = url;
    }
     
    public void Play()
    {
        BufferedInputStream bis = null;
        try 
        {
            bis = new BufferedInputStream(new FileInputStream(Url));
            player = new Player(bis);
        } 
        catch (FileNotFoundException | JavaLayerException ex) 
        {
            JOptionPane.showMessageDialog(null, "Không tìm thấy file", "Lỗi", JOptionPane.OK_OPTION);
        } 

        new Thread(new Runnable() {
            @Override
            public void run() {
                try 
                {
                    player.play();

                } catch (JavaLayerException ex) 
                {
                    Logger.getLogger(PlayMp3.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
        
    }
    
    public void Stop()
    {
        if (player != null)
        {
            player.close();
            
        }
    }

}
