/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyquancafe;

import DataProvider.ConstantClass;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author HT
 */
public class pnlQLDU extends javax.swing.JPanel {

    private CardLayout cl = new CardLayout();
    private JPanel pnlDSDU = new pnlDSDoUong();
    private JPanel pnlDSLoaiDU = new pnlDSLoaiDoUong();
    
    /**
     * Creates new form pnlQLDU
     */
    public pnlQLDU() {
        initComponents();
        
        this.setSize(ConstantClass.WIDTH_OF_CONTENT_PANEL, ConstantClass.HEIGHT_OF_CONTENT_PANEL);
        
        //JSplitPane split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnlMenu, pnlContent);
        
        //this.add(split);
        
        LoadPanelContent();
    }

    void LoadPanelContent()
    {
        pnlContent.setLayout(cl);
        
        pnlContent.add(pnlDSDU, "DS Do Uong");
        pnlContent.add(pnlDSLoaiDU, "DS Loai Do Uong");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnDSLoaiDoUong = new javax.swing.JButton();
        btnDSDoUong = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();

        btnDSLoaiDoUong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDSLoaiDoUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list drinks type.png"))); // NOI18N
        btnDSLoaiDoUong.setText("Danh sách loại đồ uống");
        btnDSLoaiDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDSLoaiDoUongMouseClicked(evt);
            }
        });

        btnDSDoUong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDSDoUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list drinks.png"))); // NOI18N
        btnDSDoUong.setText("Danh sách đồ uống");
        btnDSDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDSDoUongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(btnDSLoaiDoUong)
                .addContainerGap())
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDSDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnDSLoaiDoUong)
                .addGap(18, 18, 18)
                .addComponent(btnDSDoUong)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1073, Short.MAX_VALUE)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDSLoaiDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDSLoaiDoUongMouseClicked
        // TODO add your handling code here:
        cl.show(pnlContent, "DS Loai Do Uong");
    }//GEN-LAST:event_btnDSLoaiDoUongMouseClicked

    private void btnDSDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDSDoUongMouseClicked
        // TODO add your handling code here:
        cl.show(pnlContent, "DS Do Uong");
    }//GEN-LAST:event_btnDSDoUongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDSDoUong;
    private javax.swing.JButton btnDSLoaiDoUong;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
